language: c
compiler:
- clang
- gcc
sudo: false
before_install:
- wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz  -O /tmp/cmake.tar.gz
- tar xzf /tmp/cmake.tar.gz
- export PATH=$PWD/cmake-3.3.1-Linux-x86_64/bin/:$PATH
script:
- "./build.sh all test"
notifications:
  slack:
    secure: WdgYxQrnFR5eu/eKygPuLjlFsuZxD9m2PLRWTLT85aj+18Gp2ooPjnI9UFdb1xY87+4InhWk6PvQU35j4bG0etPQtX+0H4T4Zdk/aD6KxgJBHIYGqtfZUMmdFfVpUH9cCPx99Jjw81mhKrxM+6rXiZdiWXuNhvbJOApRT6uxE2k=
